#!/usr/bin/env python3
"""Build V2 strategy validation summaries from point-in-time recommendation data.

Inputs:
- recommendation_runs / recommendation_picks
- pick_outcomes generated by evaluate_v2_picks.py
- portfolio_plans / price_daily

Outputs:
- portfolio_performance
- factor_attribution
- strategy_review_reports
- data/latest/strategy_validation_report.json

This script does not generate today's buy list and does not change
strategy_versions. It only evaluates already-saved recommendation snapshots.
"""
from __future__ import annotations

import argparse
import json
import math
import os
import sys
from collections import defaultdict
from datetime import date, datetime
from pathlib import Path
from typing import Any

import duckdb

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "scripts" / "lib"))

from stock_db import DB_PATH  # noqa: E402
from stock_research.core import strategy_eval as se  # noqa: E402

OUT_PATH = REPO / "data" / "latest" / "strategy_validation_report.json"
FACTORS = ("valuation", "momentum", "reversal", "data_quality", "coverage")
PRODUCTION_METRICS_START_DATE = os.environ.get("STOCK_ASSISTANT_METRICS_START_DATE", "2026-05-25")
DEFAULT_STRATEGY_VERSION = os.environ.get("STOCK_ASSISTANT_STRATEGY_VERSION", "latest")


def _tables(conn: duckdb.DuckDBPyConnection) -> set[str]:
    return {str(r[0]) for r in conn.execute("SHOW TABLES").fetchall()}


def _as_date(value: Any) -> date | None:
    if value is None:
        return None
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    try:
        return datetime.strptime(str(value)[:10], "%Y-%m-%d").date()
    except Exception:
        return None


def _latest_strategy_version(conn: duckdb.DuckDBPyConnection) -> str | None:
    row = conn.execute(
        """
        SELECT strategy_version
        FROM recommendation_runs
        WHERE universe_scope = 'system_tech_universe' AND status = 'generated'
        ORDER BY generated_at DESC
        LIMIT 1
        """
    ).fetchone()
    return str(row[0]) if row and row[0] else None


def _resolve_strategy_version(conn: duckdb.DuckDBPyConnection, requested: str | None) -> str | None:
    if requested is None:
        return None
    key = str(requested).strip()
    if not key or key.lower() in {"all", "*"}:
        return None
    if key.lower() in {"latest", "current"}:
        return _latest_strategy_version(conn)
    return key


def _pearson(xs: list[float], ys: list[float]) -> float | None:
    if len(xs) < 3 or len(xs) != len(ys):
        return None
    mx = sum(xs) / len(xs)
    my = sum(ys) / len(ys)
    vx = sum((x - mx) ** 2 for x in xs)
    vy = sum((y - my) ** 2 for y in ys)
    if vx <= 0 or vy <= 0:
        return None
    return sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / math.sqrt(vx * vy)


def _conclusion(sample_size: int, avg_alpha: float | None, win_rate: float | None) -> tuple[str, str]:
    if sample_size < 20:
        return "继续观察：样本不足，不能给强结论。", "observe"
    if sample_size < 60:
        if avg_alpha is not None and avg_alpha > 0 and (win_rate or 0) >= 50:
            return "弱正向：样本仍不足，但当前 alpha 和胜率偏正。", "weak_continue"
        return "弱负向/中性：样本仍不足，暂不调参。", "observe"
    if avg_alpha is not None and avg_alpha >= 1.0 and (win_rate or 0) >= 55:
        return "策略健康：成熟样本显示正 alpha。", "continue"
    if avg_alpha is not None and (avg_alpha <= -1.0 or (win_rate or 0) < 45):
        return "策略承压：建议复核因子权重和市场分组。", "review_weights"
    return "策略中性：继续使用并观察下一批成熟样本。", "continue_observe"


def _validation_status_from_reports(reports: list[dict[str, Any]]) -> tuple[str, str]:
    if not reports:
        return (
            "WARN",
            "INSUFFICIENT_SAMPLE: 当前策略还没有可写入 strategy_review_reports 的成熟推荐样本；"
            "组合表现只能说明已有组合可回看，不能证明推荐策略有效。",
        )
    actions = {str(r.get("recommended_action") or "") for r in reports}
    if "review_weights" in actions:
        return (
            "WARN",
            "NEGATIVE_ALPHA_OR_LOW_HIT_RATE: 当前成熟样本显示负 alpha 或低胜率；"
            "推荐策略可继续观察，但不应视为已验证可依赖。",
        )
    if actions - {"continue"}:
        return (
            "WARN",
            "ACCUMULATING_OR_NEUTRAL_EVIDENCE: 已有策略报告，但结论仍是观察/中性；"
            "不应把 validation PASS 理解为策略有效。",
        )
    return "PASS", "strategy_positive_alpha_available"


def _load_outcome_summary(conn: duckdb.DuckDBPyConnection, strategy_version: str | None) -> tuple[dict, dict]:
    # 统一口径（stock_research.core.strategy_eval）：当前 strategy_version + 每天只取最后一批
    # + (推荐日,股票) 去重。旧口径 COUNT(*) 含同日多批重复 pick → n 虚高（严筛 49 实为去重后 14）。
    # signal 同时纳入 buy/strong_buy（旧 SQL 只算 buy，与严筛口径不一致）。
    run_ids = se.last_batch_run_ids(
        conn, strategy_version=strategy_version, metrics_start=PRODUCTION_METRICS_START_DATE)
    if not run_ids:
        return {}, {}
    placeholders = ",".join(["?"] * len(run_ids))
    sql = f"""
        SELECT rr.strategy_version, dpo.market, dpo.horizon,
               COUNT(*) AS sample_size,
               SUM(CASE WHEN dpo.is_success THEN 1 ELSE 0 END) AS wins,
               AVG(dpo.alpha_pct) AS avg_alpha,
               AVG(dpo.return_pct) AS avg_return,
               MIN(rr.run_date) AS period_start,
               MAX(dpo.outcome_date) AS period_end
        FROM (
            SELECT DISTINCT po.run_id, po.market, po.symbol, po.horizon,
                   po.alpha_pct, po.return_pct, po.is_success, po.outcome_date
            FROM pick_outcomes po
            JOIN recommendation_picks rp
              ON rp.run_id = po.run_id AND rp.market = po.market AND rp.symbol = po.symbol
            WHERE po.run_id IN ({placeholders})
              AND po.alpha_pct IS NOT NULL
              AND isfinite(po.alpha_pct)
              AND LOWER(COALESCE(rp.signal, rp.rating, '')) IN ('buy', 'strong_buy')
        ) dpo
        JOIN recommendation_runs rr ON rr.run_id = dpo.run_id
        GROUP BY rr.strategy_version, dpo.market, dpo.horizon
        ORDER BY rr.strategy_version, dpo.market, dpo.horizon
    """
    rows = conn.execute(sql, list(run_ids)).fetchall()
    by_strategy_market: dict[tuple[str, str], dict[str, Any]] = defaultdict(lambda: {"by_horizon": {}})
    by_market_total: dict[str, dict[str, Any]] = {}
    for strategy_version, market, horizon, n, wins, avg_alpha, avg_return, start, end in rows:
        key = (str(strategy_version), str(market))
        n_i = int(n or 0)
        wins_i = int(wins or 0)
        win_rate = wins_i / n_i * 100 if n_i else 0.0
        item = {
            "sample_size": n_i,
            "wins": wins_i,
            "win_rate": round(win_rate, 2),
            "avg_alpha": round(float(avg_alpha), 4) if avg_alpha is not None else None,
            "avg_return": round(float(avg_return), 4) if avg_return is not None else None,
            "period_start": str(start)[:10] if start else None,
            "period_end": str(end)[:10] if end else None,
        }
        by_strategy_market[key]["strategy_version"] = str(strategy_version)
        by_strategy_market[key]["market"] = str(market)
        by_strategy_market[key]["by_horizon"][str(horizon)] = item
        by_market_total.setdefault(str(market), {"sample_size": 0, "wins": 0})
        by_market_total[str(market)]["sample_size"] += n_i
        by_market_total[str(market)]["wins"] += wins_i
    return dict(by_strategy_market), by_market_total


def _write_strategy_reports(conn: duckdb.DuckDBPyConnection, grouped: dict) -> list[dict[str, Any]]:
    written: list[dict[str, Any]] = []
    generated_at = datetime.now()
    for (strategy_version, market), payload in grouped.items():
        by_h = payload.get("by_horizon") or {}
        primary = by_h.get("1d") or next(iter(by_h.values()), {})
        sample_size = int(primary.get("sample_size") or 0)
        avg_alpha = primary.get("avg_alpha")
        win_rate = primary.get("win_rate")
        conclusion, action = _conclusion(sample_size, avg_alpha, win_rate)
        starts = [_as_date(x.get("period_start")) for x in by_h.values()]
        ends = [_as_date(x.get("period_end")) for x in by_h.values()]
        period_start = min([x for x in starts if x] or [generated_at.date()])
        period_end = max([x for x in ends if x] or [generated_at.date()])
        full_payload = {
            "schema_version": "v2_strategy_validation_v1",
            "generated_at": generated_at.isoformat(timespec="seconds"),
            "strategy_version": strategy_version,
            "market": market,
            "sample_rule": "primary metrics use 1d mature outcomes; all horizons are preserved in payload",
            "by_horizon": by_h,
            "conclusion": conclusion,
            "recommended_action": action,
        }
        conn.execute(
            """
            INSERT INTO strategy_review_reports (
                strategy_version, market, period_type, period_start, period_end,
                sample_size, win_rate, avg_alpha, max_drawdown_pct,
                conclusion, recommended_action, generated_at, payload_json
            )
            VALUES (?, ?, 'daily', ?, ?, ?, ?, ?, NULL, ?, ?, ?, ?)
            ON CONFLICT (strategy_version, market, period_type, period_start, period_end)
            DO UPDATE SET
                sample_size=excluded.sample_size,
                win_rate=excluded.win_rate,
                avg_alpha=excluded.avg_alpha,
                conclusion=excluded.conclusion,
                recommended_action=excluded.recommended_action,
                generated_at=excluded.generated_at,
                payload_json=excluded.payload_json
            """,
            [
                strategy_version,
                market,
                period_start,
                period_end,
                sample_size,
                win_rate,
                avg_alpha,
                conclusion,
                action,
                generated_at,
                json.dumps(full_payload, ensure_ascii=False, sort_keys=True, default=str),
            ],
        )
        written.append(full_payload)
    return written


def _write_factor_attribution(conn: duckdb.DuckDBPyConnection, strategy_version_filter: str | None) -> list[dict[str, Any]]:
    sql = """
        SELECT rr.strategy_version, rp.market, rp.factor_scores_json, po.alpha_pct,
               rr.run_date, po.outcome_date
        FROM pick_outcomes po
        JOIN recommendation_picks rp
          ON rp.run_id = po.run_id AND rp.market = po.market AND rp.symbol = po.symbol
        JOIN recommendation_runs rr ON rr.run_id = po.run_id
        WHERE rr.universe_scope = 'system_tech_universe'
          AND rr.run_date >= ?
          AND po.horizon = '1d'
          AND po.alpha_pct IS NOT NULL
          AND COALESCE(rp.signal, 'buy') = 'buy'
    """
    params: list[Any] = [PRODUCTION_METRICS_START_DATE]
    if strategy_version_filter:
        sql += " AND rr.strategy_version = ?"
        params.append(strategy_version_filter)
    rows = conn.execute(sql, params).fetchall()
    grouped: dict[tuple[str, str], dict[str, Any]] = defaultdict(lambda: {"factors": defaultdict(list), "alphas": [], "starts": [], "ends": []})
    for strategy_version, market, factor_json, alpha, run_date, outcome_date in rows:
        try:
            factors = json.loads(factor_json) if factor_json else {}
        except Exception:
            factors = {}
        key = (str(strategy_version), str(market))
        grouped[key]["alphas"].append(float(alpha))
        grouped[key]["starts"].append(_as_date(run_date))
        grouped[key]["ends"].append(_as_date(outcome_date))
        for factor in FACTORS:
            value = factors.get(factor)
            if value is None:
                continue
            try:
                grouped[key]["factors"][factor].append(float(value))
            except Exception:
                continue

    written: list[dict[str, Any]] = []
    for (strategy_version, market), data in grouped.items():
        starts = [x for x in data["starts"] if x]
        ends = [x for x in data["ends"] if x]
        if not starts or not ends:
            continue
        period_start = min(starts)
        period_end = max(ends)
        for factor in FACTORS:
            xs = data["factors"].get(factor) or []
            ys = data["alphas"]
            corr = _pearson(xs, ys) if len(xs) == len(ys) else None
            contribution = round(float(corr) * 100, 4) if corr is not None else 0.0
            conn.execute(
                """
                INSERT INTO factor_attribution (
                    strategy_version, market, factor_name, period_start, period_end,
                    contribution_pct, sample_size, updated_at
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
                ON CONFLICT (strategy_version, market, factor_name, period_start, period_end)
                DO UPDATE SET
                    contribution_pct=excluded.contribution_pct,
                    sample_size=excluded.sample_size,
                    updated_at=excluded.updated_at
                """,
                [strategy_version, market, factor, period_start, period_end, contribution, len(ys)],
            )
            written.append({
                "strategy_version": strategy_version,
                "market": market,
                "factor_name": factor,
                "period_start": period_start.isoformat(),
                "period_end": period_end.isoformat(),
                "contribution_pct": contribution,
                "sample_size": len(ys),
            })
    return written


def _latest_close(
    conn: duckdb.DuckDBPyConnection,
    market: str,
    symbol: str,
    min_date: date,
) -> tuple[date, float] | None:
    row = conn.execute(
        """
        SELECT trade_date, close
        FROM price_daily
        WHERE market = ? AND symbol = ? AND trade_date >= ? AND close IS NOT NULL
        ORDER BY trade_date DESC, fetched_at DESC
        LIMIT 1
        """,
        [market, symbol, min_date],
    ).fetchone()
    if not row:
        return None
    return row[0], float(row[1])


def _write_portfolio_performance(conn: duckdb.DuckDBPyConnection, strategy_version: str | None) -> list[dict[str, Any]]:
    sql = """
        SELECT pp.run_id, pp.plan_version, rr.run_date
        FROM portfolio_plans pp
        JOIN recommendation_runs rr ON rr.run_id = pp.run_id
        WHERE rr.universe_scope = 'system_tech_universe'
          AND rr.run_date >= ?
    """
    params: list[Any] = [PRODUCTION_METRICS_START_DATE]
    if strategy_version:
        sql += " AND rr.strategy_version = ?"
        params.append(strategy_version)
    sql += """
        GROUP BY pp.run_id, pp.plan_version, rr.run_date
        """
    plan_keys = conn.execute(sql, params).fetchall()
    written: list[dict[str, Any]] = []
    for run_id, plan_version, run_date in plan_keys:
        rows = conn.execute(
            """
            SELECT pp.market, pp.symbol, pp.target_weight, pp.transaction_cost_bps,
                   rp.entry_price
            FROM portfolio_plans pp
            LEFT JOIN recommendation_picks rp
              ON rp.run_id = pp.run_id AND rp.market = pp.market AND rp.symbol = pp.symbol
            WHERE pp.run_id = ? AND pp.plan_version = ?
            """,
            [run_id, plan_version],
        ).fetchall()
        gross_return = 0.0
        cost_pct = 0.0
        turnover_pct = 0.0
        used = 0
        as_of: date | None = None
        for market, symbol, target_weight, bps, entry_price in rows:
            if entry_price is None or entry_price <= 0 or target_weight is None:
                continue
            close_row = _latest_close(conn, str(market), str(symbol), run_date)
            if not close_row:
                continue
            close_date, close = close_row
            as_of = close_date if as_of is None or close_date > as_of else as_of
            weight = float(target_weight)
            gross_return += weight * (close / float(entry_price) - 1) * 100
            cost_pct += weight * float(bps or 0) / 100.0
            turnover_pct += abs(weight) * 100
            used += 1
        if used == 0 or as_of is None:
            continue
        net_return = gross_return - cost_pct
        max_drawdown = max(0.0, -net_return)
        nav = 1.0 + net_return / 100.0
        conn.execute(
            """
            INSERT INTO portfolio_performance (
                run_id, plan_version, as_of_date, nav, return_pct,
                max_drawdown_pct, sharpe, calmar, turnover_pct,
                transaction_cost_pct, updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?, NULL, NULL, ?, ?, CURRENT_TIMESTAMP)
            ON CONFLICT (run_id, plan_version, as_of_date)
            DO UPDATE SET
                nav=excluded.nav,
                return_pct=excluded.return_pct,
                max_drawdown_pct=excluded.max_drawdown_pct,
                turnover_pct=excluded.turnover_pct,
                transaction_cost_pct=excluded.transaction_cost_pct,
                updated_at=excluded.updated_at
            """,
            [
                run_id,
                plan_version,
                as_of,
                round(nav, 6),
                round(net_return, 4),
                round(max_drawdown, 4),
                round(turnover_pct, 4),
                round(cost_pct, 4),
            ],
        )
        written.append({
            "run_id": run_id,
            "plan_version": plan_version,
            "as_of_date": as_of.isoformat(),
            "used_positions": used,
            "return_pct": round(net_return, 4),
            "max_drawdown_pct": round(max_drawdown, 4),
            "turnover_pct": round(turnover_pct, 4),
            "transaction_cost_pct": round(cost_pct, 4),
        })
    return written


def run(args: argparse.Namespace) -> dict[str, Any]:
    db_path = Path(args.db or DB_PATH).expanduser().resolve()
    conn = duckdb.connect(str(db_path))
    try:
        tables = _tables(conn)
        required = {
            "recommendation_runs", "recommendation_picks", "pick_outcomes",
            "portfolio_plans", "portfolio_performance", "factor_attribution",
            "strategy_review_reports", "price_daily",
        }
        missing = sorted(required - tables)
        if missing:
            raise RuntimeError(f"当前 DB 缺少 V2 策略验证表: {missing}")
        strategy_version = _resolve_strategy_version(conn, getattr(args, "strategy_version", DEFAULT_STRATEGY_VERSION))
        grouped, market_totals = _load_outcome_summary(conn, strategy_version)
        reports = _write_strategy_reports(conn, grouped)
        attribution = _write_factor_attribution(conn, strategy_version)
        portfolio = _write_portfolio_performance(conn, strategy_version)
        validation_status, status_reason = _validation_status_from_reports(reports)
        portfolio_status = "PASS" if portfolio else "WARN"
        payload = {
            "generated_at": datetime.now().isoformat(timespec="seconds"),
            "db_path": str(db_path),
            "metrics_start_date": PRODUCTION_METRICS_START_DATE,
            "strategy_version_filter": strategy_version or "all",
            "sample_policy": (
                f"Only V2 recommendation runs on/after {PRODUCTION_METRICS_START_DATE} "
                f"and matching strategy_version={strategy_version or 'all'} are included in "
                "user-facing validation; older or different-formula rows remain in DuckDB for audit."
            ),
            "status": validation_status,
            "validation_status": validation_status,
            "portfolio_status": portfolio_status,
            "status_reason": status_reason,
            "summary": {
                "strategy_review_reports_written": len(reports),
                "factor_attribution_rows_written": len(attribution),
                "portfolio_performance_rows_written": len(portfolio),
                "markets": market_totals,
            },
            "reports": reports,
            "factor_attribution": attribution,
            "portfolio_performance": portfolio,
        }
        OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        OUT_PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2, default=str), encoding="utf-8")
        return payload
    finally:
        conn.close()


def main() -> int:
    parser = argparse.ArgumentParser(description="Build V2 strategy validation summaries.")
    parser.add_argument("--db", default=os.environ.get("STOCK_DB_PATH") or str(DB_PATH))
    parser.add_argument("--strategy-version", default=DEFAULT_STRATEGY_VERSION,
                        help="默认 latest/current，只验证最新策略版本；传 all 可跨版本汇总。")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()
    payload = run(args)
    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2, default=str))
    else:
        s = payload["summary"]
        print(f"V2 strategy validation: {payload['status']}")
        print(
            f"  reports={s['strategy_review_reports_written']} "
            f"attribution={s['factor_attribution_rows_written']} "
            f"portfolio={s['portfolio_performance_rows_written']}"
        )
    return 0 if payload["status"] in {"PASS", "WARN"} else 1


if __name__ == "__main__":
    raise SystemExit(main())
